name: 'Test'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 'Run Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Use GitHub Actions'
        uses: actions/checkout@v1
      - name: 'Use Node.js 10.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'Install Package'
        run: 'npm install'
      - name: 'Run Test'
        run: 'npm test'
